# SPDX-FileCopyrightText: 2017-2020 Jens Lechtenbörger
# SPDX-FileCopyrightText: 2020 Maximilian Harl
# SPDX-License-Identifier: CC0-1.0

prepare_page:
  image: ruby:2.6
  script:
    - bundle install
    - bundle exec jekyll build -d page_
  artifacts:
    paths:
      - page_
  only:
    - master


pages:
  image: registry.gitlab.com/oer/emacs-reveal/emacs-reveal:latest
  stage: deploy
  before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive
  script:
  - mkdir -p ./public
  - cp ./page_/* ./public/
  - emacs --batch --load elisp/publish.el
  - find public -type f -regex '.*\.\(html\|js\|css\)$' -exec gzip -f -k {} \;
  artifacts:
    paths:
    - public
    expire_in: 4 weeks
  only:
  - master

