# SPDX-FileCopyrightText: 2017-2020 Jens Lechtenbörger
# SPDX-FileCopyrightText: 2020 Maximilian Harl
# SPDX-License-Identifier: CC0-1.0

# build landing page with ruby and jekyll
prepare_page:
  image: ruby:2.7
  script:
    - bundle install
    - bundle exec jekyll build -d .public
  artifacts:
    paths:
      - .public
  only:
    - master

# build reveal.js presenations with emacs-reveal
pages:
  image: registry.gitlab.com/oer/emacs-reveal/emacs-reveal:latest
  stage: deploy
  before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive
  script:
  - cp -r * .public
  - mv .public public
  - emacs --batch --load elisp/publish.el
  - find public -type f -regex '.*\.\(html\|js\|css\)$' -exec gzip -f -k {} \;
  artifacts:
    paths:
    - public
  only:
  - master

