# SPDX-FileCopyrightText: 2020 Maximilian Harl
# SPDX-License-Identifier: CC0-1.0

prepare_pages:
  image: registry.gitlab.com/oer/emacs-reveal/emacs-reveal:latest
  before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive
  script:
    - emacs --batch --load elisp/publish.el
    - find public -type f -regex '.*\.\(html\|js\|css\)$' -exec gzip -f -k {} \;
    - mkdir -p public/home
    - mv . public/home
  artifacts:
    paths:
      - public/home
  only:
    - master

pages:
  image: ruby:2.6
  script:
    - bundle install
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public
  only:
    - master

