# SPDX-FileCopyrightText: 2020 Maximilian Harl

image: registry.gitlab.com/oer/emacs-reveal/emacs-reveal:7.9.0

pages:
  stage: deploy
  before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive
  script:
  - emacs --batch --load elisp/publish.el
  - find public -type f -regex '.*\.\(html\|js\|css\)$' -exec gzip -f -k {} \;
  artifacts:
    paths:
    - public
  only:
  - master
