permalink: pretty

baseurl: "IntroCS/"

source: ./

theme: jekyll-theme-cs50

title: IntroCS


defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"

sass:
  load_paths:
    - _sass
    - _sass/node_modules
